
version: '3.4'
services:
  development_image:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        BoostVersion: 1.70.0
        BoostDirectory: boost_1_70_0
        ProtobufVersion: 3.6.1
        Project: ustevent
      target: development
    image: ustevent_development_image

  development:
    image: ustevent_development_image
    container_name: develop_ustevent
    # Uncomment if you want to expose any additional ports. The snippet below exposes port 3000.
    # ports:
    #   - 3000:3000

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
